### PR TITLE
Article: Simple grid mixins

### PR DESCRIPTION
**Pull request by goschevski**
Hi @jlong,

I created new article about creating simple grid mixin. What do you think?

### CODE REVIEW

**Comment by jlong** [comment]
@goschevski Are you still interested in seeing this published on thesassway.com? I'm working on the site again after a long hiatus.

**Comment by jlong** [comment]
@goschevski I've worked through the edits for this here: https://github.com/thesassway/thesassway.com/compare/AG_simple_grid_mixin

Have a look. If you like it we can publish it!

I left out the bit about the "fluid" class as it seemed to go against the premise of avoiding "non-semantic" classes in your markup by using mixins instead.

**Comment by goschevski** [comment]
Sure, it looks great!

Thanks.

**Comment by jlong** [comment]
It's live! http://thesassway.com/intermediate/simple-grid-mixins

Thanks!

**Pull request closed without merging**
